.PHONY: init
init:
	echo "Initializing..."
	make -f Makefile.dev build
	echo "Setting up for local provider..."
	# assuming your workstation is on Mac M1
	mkdir -p ~/.terraform.d/plugins/example.com/kelvintaywl/circleci/0.0.1/darwin_arm64
	ln -s ./terraform-provider-circleci_v0.0.1 ~/.terraform.d/plugins/example.com/kelvintaywl/circleci/0.0.1/darwin_arm64/terraform-provider-circleci_v0.0.

.PHONY: build
build:
    go fmt
	echo "Building Go binary"
	go build -o terraform-provider-circleci_v0.0.1
	make -f Makefile.dev clean_sandbox

.PHONY: clean_sandbox
clean_sandbox:
	if [ -f "sandbox/.terraform.lock.hcl" ]; then \
	  rm sandbox/.terraform.lock.hcl; \
	fi

.PHONY: test_sandbox
test_sandbox:
	terraform -chdir=sandbox fmt
	terraform -chdir=sandbox init
	terraform -chdir=sandbox validate
	terraform -chdir=sandbox plan
